### ISSUE TITLE
leadferret end user api in php

### ISSUE THREAD

**Issue by gurpreetsinghblissit** [leadferret/LeadFerret-API-PHP-SDK#1]
i want to use this api on my end please help me hoca i use it..

**Comment by gurpreetsinghblissit** [comment]
provide me a solution at my email id step by step  gurpreetsingh.blissit@gmail.com

**Comment by gurpreetsinghblissit** [comment]
i want this api credientials. please reply me

**Comment by solvire** [comment]
We can help you out if you contact our sales. info@leadferret.com
The SDK is in development.
